separating modal from wallet index into separate components.
emeth-defi-automation/portfolio-management-platform pull request #220
Opened 2024-06-03 10:25 UTC by Gawc1uuu

And moving components from global components folder closer to the place where they are used.

2024-06-03 11:15 UTC, neotheprogramist requested changes, later dismissed

2024-06-03 11:15 UTC, neotheprogramist commented on src/routes/app/wallets/_components/wallets/AddWalletModal.tsx
> +import { messagesContext } from "../../../layout";
use absolute paths with `~` instead of relative

2024-06-03 12:13 UTC, pgajek commented on src/routes/app/wallets/_components/wallets/AddWalletModal.tsx
> +  ({ isAddWalletModalOpen, stepsCounter, isSecondWalletConnected }) => {
Couldn't stepsCounter and isSecondWalletConnected be handles inside component? Or is that somehow necessary in page index?

2024-06-10 09:57 UTC, pgajek approved these changes
LGTM

2024-06-10 12:23 UTC, merged